module.exports.wordsBad = [
    'Turn Your WiFi into',
    'Earn $45/Month',
    'EASY $52',
    'Game Tester',
    'Navigation Device Host Needed',
    'Recovery Support Study',
    'Dive into Riches',
    'Android Owners Wanted',
    'Coffee Health Benefits',
    'Paid Cash Online Survey',
    'paid online study',
    'Sharing Your Thoughts in Surveys',
    'Simple System with REAL Results',
    'Help Everyone Recycle their Plastic',
    'Fintech User Experience Analyst',
    'I’ll teach you how to day trade',
    'Your Spare Time',
    'uncapped commission',
    'Mental Fog/Confusion Study',
    'Do Simple Live Chat',
    'MAKE AN EZ',
    'Paid Studies',
    'Get Paid to Post Online',
    'Earn Easy Passive Income',
    'Ecommerce UX Reviewer',
    'Mobile Games Debugger',
    'Fintech UI Debugger',
    'Fintech UX Reviewer',
    'Wep-App UI Reviewer',
    'Wep-App User Experience Reviewer',
    'TURN YOUR CELL PHONE INTO A CASH',
    'Remote Mobile App Debugger',
    'Mobile Gaming Ecosystem Tester',
    'In-App Bug Tester',
    'iOS App Reviewer',
    'Addiction Reduction',
    'SiS4 Research Study',
    'Memory Developers : AI Robotics Training',
    'SiS4 Research Study',
    '$75 to $150 Daily',
    'Earn $200',
    'Telecommute Earn $20',
    'focus group',
    'research study',
    'mentorship',
    'opioids',
    'alcohol',
    'Make Money From Home Today',
    'SPERM DONOR',
    'taskverse',
    'Social Media Marketer needed',
    'REMOTE WORK FROM HOME $97 to $375 Part-time Daily',
    'MAKE MONEY SENDING EMAILS',
    'sales rep',
    'Driver Needed',
    'Graphic Designer Needed',
    'PAID Tech Study',
    'REMOTE WORK FROM HOME $100 to $400 Part-time Daily',
    'Amazon gift card',
    'No experience required',
    'Vacation Planner',
]
