export const wordsGood = [
    'javascript',
    'react',
    'developer',
    'engineer',
    'code',
    'script',
    'software',
    'programmer',
    'programer',
    'angular',
    'haskell',
    'lisp',
    'sql',
    'python',
    'ruby',
    'php',
    'node',
    'flutter',
    'app',
    'clone',
    'website',
    'Technical Co-Founder', 'Technical CoFounder', 'Technical Co Founder',
    'e-commerce website', 'ecommerce website',
    'html',
    'css',
    'system',
    'engine',
]
